// Generated by the rpc compiler.  DO NOT EDIT!

package easyrpc

import (
	"fmt"
	"foundation/framework/component"
	"foundation/framework/component/ifs"
	"foundation/framework/g"
	"foundation/message"

	"github.com/golang/protobuf/proto"
)

//RegisterPlayerService 玩家消息
func RegisterPlayerService(service RPCServicePlayer) {
	//Login 登录
	c := g.Root.GetComponent(component.NatsCom).(ifs.INatsComponent)
	c.RegisterEvent(20000,
		func(uid uint64, cmd uint32, b []byte) error {
			a := service.GetSenderDelegate(uid)
			if nil == a {
				return fmt.Errorf("no found user =%d, cmd =%d", uid, cmd)
			}
			in := &message.CS_Login{}
			err := proto.Unmarshal(b, in)
			if err != nil {
				return fmt.Errorf("message.CS_Login Unmarshal error: %s", err.Error())
			}
			service.Login(a, in)
			return nil
		})
}
