// Generated by the rpc compiler.  DO NOT EDIT!

package playerrpc

import (
	"fmt"
	"foundation/framework/component"
	"foundation/framework/component/ifs"
	"foundation/framework/g"
	"foundation/message"

	"github.com/golang/protobuf/proto"
)

//RegisterPlayerService 玩家消息
func RegisterPlayerService(service RPCServicePlayer) {
	//Login 登录
	c := g.Root.GetComponent(component.NatsCom).(ifs.INatsComponent)
	c.RegisterEvent(20000,
		func(req *message.NatsRequest) error {
			a := GetPlayer(req.Uid)
			if nil == a {
				return fmt.Errorf("no found user =%d, cmd =%d", req.Uid, req.Cmd)
			}
			in := &message.CS_Login{}
			err := proto.Unmarshal(req.Data, in)
			if err != nil {
				return fmt.Errorf("message.CS_Login Unmarshal error: %s", err.Error())
			}
			r := service.Login(a, in)
			data, e := proto.Marshal(r)
			if e != nil {
				return fmt.Errorf("message.SC_Login Unmarshal error:%s", e.Error())
			}
			rep := &message.NatsReply{
				Uid:  req.Uid,
				Cmd:  req.Cmd,
				Data: data,
				Code: message.Code_OK,
			}
			c.Reply(req.ReplayUrl, rep)
			return nil
		})
}
