// Generated by the rpc compiler.  DO NOT EDIT!

package playerrpc

import (
	"foundation/home/player"
	"foundation/message"
)

//RPCServicePlayer 玩家相关
type RPCServicePlayer interface {
	//Login //获得玩家数据
	Login(player *player.PlayerActor, in *message.CS_Login) *message.SC_Login
}
