// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: cs.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//公共消息体，空请求,空回复，可拆分使用
type CS_EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CS_EmptyRequest) Reset() {
	*x = CS_EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_EmptyRequest) ProtoMessage() {}

func (x *CS_EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_EmptyRequest.ProtoReflect.Descriptor instead.
func (*CS_EmptyRequest) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{0}
}

type SC_EmptyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *CommonSyncData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` //公共同步的数据
}

func (x *SC_EmptyReply) Reset() {
	*x = SC_EmptyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_EmptyReply) ProtoMessage() {}

func (x *SC_EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_EmptyReply.ProtoReflect.Descriptor instead.
func (*SC_EmptyReply) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{1}
}

func (x *SC_EmptyReply) GetData() *CommonSyncData {
	if x != nil {
		return x.Data
	}
	return nil
}

//公共消息题，同步数据给客户端
type S_SyncData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *CommonSyncData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` //公共同步的数据
}

func (x *S_SyncData) Reset() {
	*x = S_SyncData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_SyncData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_SyncData) ProtoMessage() {}

func (x *S_SyncData) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_SyncData.ProtoReflect.Descriptor instead.
func (*S_SyncData) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{2}
}

func (x *S_SyncData) GetData() *CommonSyncData {
	if x != nil {
		return x.Data
	}
	return nil
}

//--------------------------------------------------------------------------------------------------通用回复数据
type CommonSyncData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommonSyncData) Reset() {
	*x = CommonSyncData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonSyncData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonSyncData) ProtoMessage() {}

func (x *CommonSyncData) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonSyncData.ProtoReflect.Descriptor instead.
func (*CommonSyncData) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{3}
}

//-------------------------------------------------------------------------------------玩家
type CS_Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CS_Ping) Reset() {
	*x = CS_Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_Ping) ProtoMessage() {}

func (x *CS_Ping) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_Ping.ProtoReflect.Descriptor instead.
func (*CS_Ping) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{4}
}

type SC_Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SC_Pong) Reset() {
	*x = SC_Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_Pong) ProtoMessage() {}

func (x *SC_Pong) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_Pong.ProtoReflect.Descriptor instead.
func (*SC_Pong) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{5}
}

//请求玩家所有数据
type CS_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Extend uint64 `protobuf:"varint,2,opt,name=extend,proto3" json:"extend,omitempty"`
}

func (x *CS_Login) Reset() {
	*x = CS_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_Login) ProtoMessage() {}

func (x *CS_Login) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_Login.ProtoReflect.Descriptor instead.
func (*CS_Login) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{6}
}

func (x *CS_Login) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CS_Login) GetExtend() uint64 {
	if x != nil {
		return x.Extend
	}
	return 0
}

//返回玩家所有数据
type SC_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Player `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` //玩家数据
}

func (x *SC_Login) Reset() {
	*x = SC_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_Login) ProtoMessage() {}

func (x *SC_Login) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_Login.ProtoReflect.Descriptor instead.
func (*SC_Login) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{7}
}

func (x *SC_Login) GetData() *Player {
	if x != nil {
		return x.Data
	}
	return nil
}

type UniqueItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                   //唯一id
	Tid         uint32 `protobuf:"varint,2,opt,name=tid,proto3" json:"tid,omitempty"`                 //模版id
	Count       uint64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`             //数量
	ExpiredTime int64  `protobuf:"varint,4,opt,name=expiredTime,proto3" json:"expiredTime,omitempty"` //过期时间
}

func (x *UniqueItem) Reset() {
	*x = UniqueItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniqueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueItem) ProtoMessage() {}

func (x *UniqueItem) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueItem.ProtoReflect.Descriptor instead.
func (*UniqueItem) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{8}
}

func (x *UniqueItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UniqueItem) GetTid() uint32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *UniqueItem) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UniqueItem) GetExpiredTime() int64 {
	if x != nil {
		return x.ExpiredTime
	}
	return 0
}

//玩家数据
type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       uint64            `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                                                                                       //id
	Name      string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                                      //名字
	Rid       uint32            `protobuf:"varint,3,opt,name=rid,proto3" json:"rid,omitempty"`                                                                                                       //角色类型id
	PropBag   map[uint32]uint64 `protobuf:"bytes,20,rep,name=propBag,proto3" json:"propBag,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`     //属性背包[如经验]
	ItemBag   map[uint32]uint64 `protobuf:"bytes,21,rep,name=itemBag,proto3" json:"itemBag,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`     //道具背包[]
	UniqueBag map[uint64]uint64 `protobuf:"bytes,22,rep,name=uniqueBag,proto3" json:"uniqueBag,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //唯一道具背包[如点券]
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{9}
}

func (x *Player) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetRid() uint32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *Player) GetPropBag() map[uint32]uint64 {
	if x != nil {
		return x.PropBag
	}
	return nil
}

func (x *Player) GetItemBag() map[uint32]uint64 {
	if x != nil {
		return x.ItemBag
	}
	return nil
}

func (x *Player) GetUniqueBag() map[uint64]uint64 {
	if x != nil {
		return x.UniqueBag
	}
	return nil
}

var File_cs_proto protoreflect.FileDescriptor

var file_cs_proto_rawDesc = []byte{
	0x0a, 0x08, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x0a, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x11, 0x0a,
	0x0f, 0x43, 0x53, 0x5f, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x3c, 0x0a, 0x0d, 0x53, 0x43, 0x5f, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x53, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x39,
	0x0a, 0x0a, 0x53, 0x5f, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x79, 0x6e, 0x63, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x22, 0x09, 0x0a, 0x07, 0x43,
	0x53, 0x5f, 0x50, 0x69, 0x6e, 0x67, 0x22, 0x09, 0x0a, 0x07, 0x53, 0x43, 0x5f, 0x50, 0x6f, 0x6e,
	0x67, 0x22, 0x38, 0x0a, 0x08, 0x43, 0x53, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x22, 0x2f, 0x0a, 0x08, 0x53,
	0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x66, 0x0a, 0x0a,
	0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0xa8, 0x03, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02, 0x30, 0x01,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x07, 0x70,
	0x72, 0x6f, 0x70, 0x42, 0x61, 0x67, 0x18, 0x14, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x50, 0x72,
	0x6f, 0x70, 0x42, 0x61, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x70,
	0x42, 0x61, 0x67, 0x12, 0x36, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x42, 0x61, 0x67, 0x18, 0x15,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x61, 0x67, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x42, 0x61, 0x67, 0x12, 0x3c, 0x0a, 0x09, 0x75,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x42, 0x61, 0x67, 0x18, 0x16, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e,
	0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x42, 0x61, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09,
	0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x42, 0x61, 0x67, 0x1a, 0x3a, 0x0a, 0x0c, 0x50, 0x72, 0x6f,
	0x70, 0x42, 0x61, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3a, 0x0a, 0x0c, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x61, 0x67,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x1a, 0x3c, 0x0a, 0x0e, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x42, 0x61, 0x67, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42,
	0x0a, 0x5a, 0x08, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_cs_proto_rawDescOnce sync.Once
	file_cs_proto_rawDescData = file_cs_proto_rawDesc
)

func file_cs_proto_rawDescGZIP() []byte {
	file_cs_proto_rawDescOnce.Do(func() {
		file_cs_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_proto_rawDescData)
	})
	return file_cs_proto_rawDescData
}

var file_cs_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_cs_proto_goTypes = []interface{}{
	(*CS_EmptyRequest)(nil), // 0: message.CS_EmptyRequest
	(*SC_EmptyReply)(nil),   // 1: message.SC_EmptyReply
	(*S_SyncData)(nil),      // 2: message.S_SyncData
	(*CommonSyncData)(nil),  // 3: message.CommonSyncData
	(*CS_Ping)(nil),         // 4: message.CS_Ping
	(*SC_Pong)(nil),         // 5: message.SC_Pong
	(*CS_Login)(nil),        // 6: message.CS_Login
	(*SC_Login)(nil),        // 7: message.SC_Login
	(*UniqueItem)(nil),      // 8: message.UniqueItem
	(*Player)(nil),          // 9: message.Player
	nil,                     // 10: message.Player.PropBagEntry
	nil,                     // 11: message.Player.ItemBagEntry
	nil,                     // 12: message.Player.UniqueBagEntry
}
var file_cs_proto_depIdxs = []int32{
	3,  // 0: message.SC_EmptyReply.data:type_name -> message.CommonSyncData
	3,  // 1: message.S_SyncData.data:type_name -> message.CommonSyncData
	9,  // 2: message.SC_Login.data:type_name -> message.Player
	10, // 3: message.Player.propBag:type_name -> message.Player.PropBagEntry
	11, // 4: message.Player.itemBag:type_name -> message.Player.ItemBagEntry
	12, // 5: message.Player.uniqueBag:type_name -> message.Player.UniqueBagEntry
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_cs_proto_init() }
func file_cs_proto_init() {
	if File_cs_proto != nil {
		return
	}
	file_code_proto_init()
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_EmptyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_SyncData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonSyncData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniqueItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cs_proto_goTypes,
		DependencyIndexes: file_cs_proto_depIdxs,
		MessageInfos:      file_cs_proto_msgTypes,
	}.Build()
	File_cs_proto = out.File
	file_cs_proto_rawDesc = nil
	file_cs_proto_goTypes = nil
	file_cs_proto_depIdxs = nil
}
