// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: in.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InID int32

const (
	InID_None  InID = 0
	InID_Login InID = 1000
	InID_MAX   InID = 9999
)

// Enum value maps for InID.
var (
	InID_name = map[int32]string{
		0:    "None",
		1000: "Login",
		9999: "MAX",
	}
	InID_value = map[string]int32{
		"None":  0,
		"Login": 1000,
		"MAX":   9999,
	}
)

func (x InID) Enum() *InID {
	p := new(InID)
	*p = x
	return p
}

func (x InID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InID) Descriptor() protoreflect.EnumDescriptor {
	return file_in_proto_enumTypes[0].Descriptor()
}

func (InID) Type() protoreflect.EnumType {
	return &file_in_proto_enumTypes[0]
}

func (x InID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InID.Descriptor instead.
func (InID) EnumDescriptor() ([]byte, []int) {
	return file_in_proto_rawDescGZIP(), []int{0}
}

var File_in_proto protoreflect.FileDescriptor

var file_in_proto_rawDesc = []byte{
	0x0a, 0x08, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2a, 0x26, 0x0a, 0x04, 0x49, 0x6e, 0x49, 0x44, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0xe8,
	0x07, 0x12, 0x08, 0x0a, 0x03, 0x4d, 0x41, 0x58, 0x10, 0x8f, 0x4e, 0x42, 0x0a, 0x5a, 0x08, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_in_proto_rawDescOnce sync.Once
	file_in_proto_rawDescData = file_in_proto_rawDesc
)

func file_in_proto_rawDescGZIP() []byte {
	file_in_proto_rawDescOnce.Do(func() {
		file_in_proto_rawDescData = protoimpl.X.CompressGZIP(file_in_proto_rawDescData)
	})
	return file_in_proto_rawDescData
}

var file_in_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_in_proto_goTypes = []interface{}{
	(InID)(0), // 0: message.InID
}
var file_in_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_in_proto_init() }
func file_in_proto_init() {
	if File_in_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_in_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_in_proto_goTypes,
		DependencyIndexes: file_in_proto_depIdxs,
		EnumInfos:         file_in_proto_enumTypes,
	}.Build()
	File_in_proto = out.File
	file_in_proto_rawDesc = nil
	file_in_proto_goTypes = nil
	file_in_proto_depIdxs = nil
}
