--Generated by the rpc compiler.  DO NOT EDIT!

local networkDataRules = {
	d = {

		--test.h
		--//进入竞技场 (涉及到离线数据，走异步)
		[21700] = { "RequestEnterArena", "cl.PlaceHolder", "cl.SC_EnterArena" },

		--//开始战斗 (涉及到离线数据，走异步)
		[21702] = { "RequestBeginArenaBattle", "cl.CS_BeginArenaBattle", "cl.SC_BeginArenaBattle" },

		--//战斗结果->胜利验证->同时回传需要翻牌的数据
		[21703] = { "RequestArenaBattleResult", "cl.CS_ArenaBattleResult", "cl.SC_ArenaBattleResult" },

		--//扫荡
		[21704] = { "Sweep", "cl.CS_SweepArena", "cl.SC_SweepArena" },

		--//兑换
		[21705] = { "ArenaExchange", "cl.CS_ExchangeIdx", "cl.SC_ExchangeIdx" },

		--//排行
		[21706] = { "RequestGetArenaRank", "cl.CS_ArenaRank", "cl.SC_ArenaRank" },

		--//战报
		[21707] = { "ArenaBattleLog", "cl.PlaceHolder", "cl.SC_ArenaBattleLog" },

		--//购买竞技场挑战次数
		[21708] = { "BuyArenaChallengeTimes", "cl.PlaceHolder", "cl.SC_BuyArenaChallengeTimes" },

		--//被攻击排名发生变化通知
		[21709] = { "PushArenaRankChange", "", "cl.PlaceHolder" },

		--//战斗次数奖励
		[21910] = { "GetBattleTimesReward", "cl.CS_ExchangeIdx", "cl.SC_CommonRet" },


	},
	k = {
		 RequestEnterArena = 21700 ,
		 RequestBeginArenaBattle = 21702 ,
		 RequestArenaBattleResult = 21703 ,
		 Sweep = 21704 ,
		 ArenaExchange = 21705 ,
		 RequestGetArenaRank = 21706 ,
		 ArenaBattleLog = 21707 ,
		 BuyArenaChallengeTimes = 21708 ,
		 PushArenaRankChange = 21709 ,
		 GetBattleTimesReward = 21910 ,
	},
} return networkDataRules
